# $OpenBSD: dot.cshrc,v 1.11 2022/08/10 07:40:37 tb Exp $
#
# csh initialization

alias df	df -k
alias du	du -k
alias f		finger
alias h		'history -r | more'
alias j		jobs -l
alias la	ls -a
alias lf	ls -FA
alias ll	ls -lsA
alias tset	'set noglob histchars=""; eval `\tset -s \!*`; unset noglob histchars'
alias z		suspend

set path = (~/bin /bin /sbin /usr/{bin,sbin,X11R6/bin,local/bin,local/sbin})

if ($?prompt) then
	# An interactive shell -- set some stuff up
	set filec
	set history = 1000
	set ignoreeof
	set mail = (/var/mail/$USER)
	set mch = `hostname -s`
	alias prompt 'set prompt = "$mch:q"":$cwd:t {\!} "'
	alias cd 'cd \!*; prompt'
	alias chdir 'cd \!*; prompt'
	alias popd 'popd \!*; prompt'
	alias pushd 'pushd \!*; prompt'
	cd .
	umask 22
endif

# Personal configs

setenv EDITOR	'nvim'
setenv PAGER	'less'

# Personal exports

setenv QT_QPA_PLATFORMTHEME 'qt6ct'
setenv XDG_RUNTIME_DIR '/tmp/run/user/1000'
setenv AUDIODEVICE 'snd/1'
setenv AUDIOPLAYDEVICE 'snd/1'
setenv AUDIORECDEVICE 'snd/1'
setenv GOPATH '/home/yukiteru/.golang'
setenv PARALLEL_BUILD 'YES'
setenv MAKE_JOBS 4
setenv RUST_SRC_PATH '/usr/local/lib/rustlib/src/rust/library'
setenv CVSROOT 'anoncvs@anoncvs.spacehopper.org:/cvs'
setenv MOZ_ACCELERATED 1
setenv MOZ_WEBRENDER 1
setenv XCURSOR_SIZE 16
setenv FREETYPE_PROPERTIES "cff:no-stem-darkening=0.0 autofitter:no-stem-darkening=0.0"
setenv XKB_DEFAULT_LAYOUT "us"
setenv XKB_DEFAULT_VARIANT "intl"

# Language setting for user
setenv LANG 'es_ES.UTF-8'
setenv CHARSET 'UTF-8'
