# $OpenBSD: dot.cshrc,v 1.11 2022/08/10 07:40:37 tb Exp $
#
# csh initialization

alias df	df -k
alias du	du -k
alias f		finger
alias h		'history -r | more'
alias j		jobs -l
alias la	ls -a
alias lf	ls -FA
alias ll	ls -lsA
alias tset	'set noglob histchars=""; eval `\tset -s \!*`; unset noglob histchars'
alias z		suspend

set path = (~/.golang/bin ~/.cargo/bin ~/.config/emacs/bin ~/.local/bin ~/bin /bin /sbin /usr/{bin,sbin,X11R6/bin,local/bin,local/sbin})

if ($?prompt) then
	# An interactive shell -- set some stuff up
	set filec
	set history = 1000
	set ignoreeof
	set mail = (/var/mail/$USER)
	set mch = `hostname -s`
	alias prompt 'set prompt = "$mch:q"":$cwd:t {\!} "'
	alias cd 'cd \!*; prompt'
	alias chdir 'cd \!*; prompt'
	alias popd 'popd \!*; prompt'
	alias pushd 'pushd \!*; prompt'
	cd .
	umask 22
endif

# Personal configs
setenv EDITOR	'nvim'
setenv PAGER	'less'

# # Personal exports
setenv QT_QPA_PLATFORMTHEME 'qt5ct'
setenv XDG_RUNTIME_DIR '/home/yukiteru/.local/run/yukiteru'
setenv AUDIODEVICE 'snd/0'
setenv AUDIOPLAYDEVICE 'snd/0'
setenv AUDIORECDEVICE 'snd/0'
setenv GOPATH '/home/yukiteru/.golang'
setenv PARALLEL_BUILD 'YES'
setenv MAKE_JOBS 4
setenv RUST_SRC_PATH '/usr/local/lib/rustlib/src/rust/library'
setenv CVSROOT 'anoncvs@anoncvs.spacehopper.org:/cvs'
setenv PIPENV_VENV_IN_PROJECT 1
setenv MOZ_ACCELERATED 1
setenv MOZ_WEBRENDER 1
setenv RESTIC_REPOSITORY '/mnt/Backups'

# # Language setting for user
setenv LANG 'es_ES.UTF-8'
setenv CHARSET 'UTF-8'

