# ENV for the X11 session
export LANG="es_ES.UTF-8"
export CHARSET="UTF-8"
export EDITOR="nvim"
export PAGER="less"
export QT_QPA_PLATFORMTHEME="qt5ct"
export XDG_RUNTIME_DIR="/tmp/run/user/1000"
export AUDIODEVICE="snd/1"
export AUDIOPLAYDEVICE="snd/1"
export AUDIORECDEVICE="snd/1"
export CVSROOT="anoncvs@anoncvs.spacehopper.org:/cvs"
export PARALLEL_BUILD="yes"
export MAKE_JOBS=4
export GOPATH="${HOME}/.golang"
export RUST_SRC_PATH="/usr/local/lib/rustlib/src/rust/library"
export MOZ_ACCELERATED=1
export MOZ_WEBRENDER=1

# Dbus session
if [ -x /usr/local/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
        eval `dbus-launch --sh-syntax --exit-with-x11`
fi

# Init i3 session
exec /usr/local/bin/ck-launch-session /usr/local/bin/i3
