# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        output_format = "i3bar"
        colors = true
        interval = 5
	color_good = "#99E900"
	color_degraded = "#C8E3FF"
	color_bad = "#FF0000"
}

order += "ethernet _first_"
order += "disk /"
order += "disk /home"
order += "load"
order += "cpu_temperature cpu0"
order += "volume master"
order += "tztime local"
 
cpu_temperature cpu0 {
         format = "CPU Temp: %degrees C"
         path = "ksmn0"
}

ethernet _first_ {
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

disk "/" {
        format = "/: %avail"
}

disk "/home" {
        format = "/home: %avail"
}

volume master {
	format = "vol: %volume"
}

load {
        format = "Load: %1min"
}

memory {
        format = "%used | %available"
        threshold_degraded = "1G"
        format_degraded = "MEMORY < %available"
}

tztime local {
        format = "%Y-%m-%d %H:%M:%S"
}
