# Enabling HT support in OpenBSD
hw.smt=1

# Max files in kernel
kern.maxfiles=16384

# Aperture for xenocara
machdep.allowaperture=1

# Forwarding
net.inet.ip.forwarding=1

# HPET
kern.timecounter.hardware=acpihpet0
