switch "vmnet" {
    interface bridge0
}

vm "alpine" {
    disable
    memory 2G
    cdrom "/home/yukiteru/WORK/VMs/alpine-virt-3.17.0-x86_64.iso"
    disk "/home/yukiteru/WORK/VMs/alpine.img"
    interface tap { lladdr fe:e1:bb:d1:25:11 switch "vmnet" }
}
